import { Agent, Category } from "@/types";

export const agentsData: Agent[] = [
  {
    id: "1",
    slug: "support-responder",
    name: "Support Responder",
    description: "Intelligent customer support agent that handles inquiries with empathy and accuracy.",
    category: "Customer Support",
    price: 49,
    rating: 4.9,
    usageCount: 15420,
    icon: "🎧",
    isFeatured: true,
  },
  {
    id: "2",
    slug: "support-analytics",
    name: "Support Analytics",
    description: "Deep analytics and insights for your support operations.",
    category: "Customer Support",
    price: 39,
    rating: 4.7,
    usageCount: 8930,
    icon: "📊",
    isNew: true,
  },
  {
    id: "3",
    slug: "sales-engineer",
    name: "Sales Engineer",
    description: "Technical sales agent that qualifies leads and demos products.",
    category: "Sales",
    price: 79,
    rating: 4.8,
    usageCount: 12100,
    icon: "💼",
    isNew: true,
  },
  {
    id: "4",
    slug: "sales-coach",
    name: "Sales Coach",
    description: "AI-powered sales training and coaching agent.",
    category: "Sales",
    price: 59,
    rating: 4.6,
    usageCount: 6780,
    icon: "💼",
  },
  {
    id: "5",
    slug: "outbound-strategist",
    name: "Outbound Strategist",
    description: "Strategic agent for outbound campaigns and lead generation.",
    category: "Sales",
    price: 69,
    rating: 4.7,
    usageCount: 5420,
    icon: "💼",
  },
  {
    id: "6",
    slug: "code-reviewer",
    name: "Code Reviewer",
    description: "Automated code review with security and best practices checks.",
    category: "Engineering",
    price: 39,
    rating: 4.7,
    usageCount: 23100,
    icon: "⚙️",
  },
  {
    id: "7",
    slug: "frontend-developer",
    name: "Frontend Developer",
    description: "Full-stack frontend development agent with modern frameworks.",
    category: "Engineering",
    price: 89,
    rating: 4.8,
    usageCount: 18700,
    icon: "⚙️",
  },
  {
    id: "8",
    slug: "backend-architect",
    name: "Backend Architect",
    description: "Scalable backend architecture and API design specialist.",
    category: "Engineering",
    price: 99,
    rating: 4.9,
    usageCount: 12300,
    icon: "⚙️",
  },
  {
    id: "9",
    slug: "devops-automator",
    name: "DevOps Automator",
    description: "CI/CD pipelines, infrastructure as code, and deployment automation.",
    category: "Engineering",
    price: 79,
    rating: 4.8,
    usageCount: 8900,
    icon: "⚙️",
    isNew: true,
  },
  {
    id: "10",
    slug: "ui-designer",
    name: "UI Designer",
    description: "Beautiful, modern UI designs with accessibility in mind.",
    category: "Design",
    price: 59,
    rating: 4.9,
    usageCount: 11200,
    icon: "🎨",
    isNew: true,
  },
  {
    id: "11",
    slug: "ux-researcher",
    name: "UX Researcher",
    description: "User research synthesis and usability analysis.",
    category: "Design",
    price: 49,
    rating: 4.6,
    usageCount: 4560,
    icon: "🎨",
  },
  {
    id: "12",
    slug: "brand-guardian",
    name: "Brand Guardian",
    description: "Brand consistency checker and design system enforcer.",
    category: "Design",
    price: 45,
    rating: 4.7,
    usageCount: 3890,
    icon: "🎨",
  },
  {
    id: "13",
    slug: "financial-analyst",
    name: "Financial Analyst",
    description: "Investment analysis, portfolio tracking, and market insights.",
    category: "Finance",
    price: 89,
    rating: 4.6,
    usageCount: 7890,
    icon: "💰",
  },
  {
    id: "14",
    slug: "bookkeeper",
    name: "Bookkeeper",
    description: "Automated bookkeeping and expense tracking.",
    category: "Finance",
    price: 59,
    rating: 4.8,
    usageCount: 5430,
    icon: "💰",
  },
  {
    id: "15",
    slug: "document-generator",
    name: "Document Generator",
    description: "Automated contract and document generation with templates.",
    category: "Productivity",
    price: 29,
    rating: 4.8,
    usageCount: 18900,
    icon: "✨",
  },
  {
    id: "16",
    slug: "workflow-architect",
    name: "Workflow Architect",
    description: "Business process automation and workflow design.",
    category: "Productivity",
    price: 79,
    rating: 4.7,
    usageCount: 6780,
    icon: "✨",
    isNew: true,
  },
  {
    id: "17",
    slug: "legal-doc-review",
    name: "Legal Doc Review",
    description: "Contract analysis and legal document review automation.",
    category: "Productivity",
    price: 99,
    rating: 4.9,
    usageCount: 4320,
    icon: "✨",
  },
  {
    id: "18",
    slug: "recruitment-specialist",
    name: "Recruitment Specialist",
    description: "Resume screening, candidate matching, and interview scheduling.",
    category: "Productivity",
    price: 49,
    rating: 4.7,
    usageCount: 5670,
    icon: "✨",
  },
];

export const categories: Category[] = [
  { id: "1", name: "Customer Support", slug: "support", icon: "🎧", agentCount: 2 },
  { id: "2", name: "Sales", slug: "sales", icon: "💼", agentCount: 3 },
  { id: "3", name: "Engineering", slug: "engineering", icon: "⚙️", agentCount: 4 },
  { id: "4", name: "Design", slug: "design", icon: "🎨", agentCount: 3 },
  { id: "5", name: "Finance", slug: "finance", icon: "💰", agentCount: 2 },
  { id: "6", name: "Productivity", slug: "productivity", icon: "✨", agentCount: 4 },
];

export function getAgentBySlug(slug: string): Agent | undefined {
  return agentsData.find((agent) => agent.slug === slug);
}

export function getAgentsByCategory(category: string): Agent[] {
  return agentsData.filter((agent) => agent.category.toLowerCase() === category.toLowerCase());
}
